---
name: Create and publish image

on:
  push:
    branches: ["main", "develop"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout github.repository
        uses: actions/checkout@v3.5.3

      - name: Login to registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          build-args: |
            "ARG_DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "ARG_NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}"
            "ARG_NEXT_PUBLIC_SECRET=${{ secrets.NEXT_PUBLIC_SECRET }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
